### ISSUE TITLE
How should we handle responsive breakpoints?

### ISSUE THREAD

**Issue by pixelastic** [algolia/documentation-search#6]
Taking eslint as an example, here is how we currently handle the various screen sizes:

![image](https://cloud.githubusercontent.com/assets/283419/11724250/3896d35e-9f73-11e5-9cad-6073e41df26b.png)
Simple dropdown with only the heading displayed

![image](https://cloud.githubusercontent.com/assets/283419/11724259/470e25c2-9f73-11e5-838d-cf331d341062.png)
Same dropdown, but we have enough space to also add a snippet

![image](https://cloud.githubusercontent.com/assets/283419/11724266/4db13df6-9f73-11e5-93c3-aad2823e06de.png)
More space, we can add a secondary column and let the content breathe

![image](https://cloud.githubusercontent.com/assets/283419/11724570/26971978-9f75-11e5-939d-9d07f5ffb1f6.png)

Same as before, but the search input is just a part of the header, it no longer takes all the available space

I think this is a very important feature, that we should keep in our implementations. But I fail to see how we can do that in a generic way (ie. works for every design), or how to easily let users tweak it.

Here are the main problems:
- It is, in essence, really bound to the breakpoints defined in the parent layout (depending on the number of elements in the main menu, not all websites will change the display at the same breakpoints). 
- The dropdown being `position:absolute`, all `left`/`right`/`top`/`width` values are dependent on the parent markup
- All the CSS code is thought as mobile-first. We set default styles for small mobile screens and only add more columns as the page width increases.
- I cannot simply add `left: -20px`, `right: -20px` for small screens and `left: 0`, `max-width: 430px` for bigger screen, this will make no sense for some layout.

If you have any ideas to solve the issues, or just comments on how, as users you would expect this to work, please, shoot.

cc @redox @vvo @ElPicador @bobylito @proudlygeek @alexandremeunier @Shipow @dustincoates  @kokliKo @Jerskouille

**Comment by ElPicador** [comment]
We discussed it with @pixelastic, and I think we do not really care about responsivness for a v1. 
Most technical documentation are not meant to be seen on a mobile phone. You are almost always on a computer/tablet when searching/reading this kind of doc.

It's true a lot of docs are made with bootstrap, so we could use the break points of bootstrap in the v1, and @pixelastic has already done it on the bootstrap's doc.

But, I think our major issue will be docs with iframes, like [javadocs](https://docs.oracle.com/javase/8/docs/api/) or [ruby](http://ruby-doc.org/stdlib-2.2.3/), as I have no idea how to integrate properly our searchbar

**Comment by vvo** [comment]
> You are almost always on a computer/tablet when searching/reading this kind of doc.

Yep maybe for a first version we can just hide the search for very small screens.

Also we can wait for the doc search to be used and required to work in very small screen situation to pop out and see what we do with them

**Comment by pixelastic** [comment]
OK, thanks for your feedbacks. Closing it now.
